export const GET_URL = "http://localhost:3001/";

export const GET_PRODUCTS_ALL = "GET_PRODUCTS_ALL";
export const GET_PRODUCTS_BY_NAME = "GET_PRODUCTS_BY_NAME";
export const GET_PRODUCTS_FOR_CATEGORY = "GET_PRODUCTS_FOR_CATEGORY";
export const GET_PRODUCT_DETAIL = "GET_PRODUCT_DETAIL";
export const GET_USERS = "GET_USERS";
export const GET_USER_DETAIL = "GET_USER_DETAIL";
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER_DETAIL = "GET_ORDER_DETAIL";
export const ADD_USER = "ADD_USER";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_USER = "DELETE_USER";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const LOADING = "LOADING";
export const RESET = "RESET";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const MODIFY_ITEM_CART = "MODIFY_ITEM_CART";
export const FILTERED_BY_CATEGORY = "FILTRED_FOR_CATEGORY";
export const GET_VARIETALS = "GET_VARIETALS";
export const FILTER_STATE = "FILTER_STATE";
export const SORTS="SORTS"
export const CHANGE_SORT_STATE="CHANGE_SORT_STATE";
export const LOG_IN = "LOG_IN";
export const LOAD_PROFILE = "LOAD_PROFILE";
